load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

cc_library(
    name = "spsc_queue",
    hdrs = ["include/spsc_queue.hpp"],
    strip_include_prefix = "include",
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "spsc_benchmark",
    srcs = ["main.cpp"],
    linkopts = ["-pthread"],
    deps = [
        ":spsc_queue",
        "//benchmarks:benchmarks",
    ],
)
